"""Load compiled events restricted to the post-fire analysis window.

Every analysis takes its events through here, so the scope decision lives in
one place instead of being re-implemented per script.

The window
----------
`POSTFIRE_WINDOW_YEARS = 2.0`, set 2026-09-20. Postfire debris-flow
susceptibility is concentrated in the first wet season or two after fire, and
an event five or twenty years later is a different population. The compilation
keeps those records — it is a database — and this filter defines what the
seasonality analysis treats as postfire.

What the window does NOT do
---------------------------
It is a scope decision, not a process filter, and it is a poor instrument for
removing landslide-initiated flows. Measured on the 345-event compilation:

    landslide-involved events within 2 yr : 6   (three under six months)
    landslide-involved events beyond 2 yr : 7
    runoff-generated events beyond 2 yr   : 34

So the window keeps nearly half the landslide events and discards five times as
many runoff-generated events as landslide ones. Shallow landslides in the
western Cascades appear about five months after fire. To exclude landslide
initiation, filter `initiation_class` — but only two of the eight point sources
(`literature` and `oregon2024`) actually report it; the rest are assumed
runoff-generated by the loader, on the strength of their titles. See
`scripts/checks/date_basis_audit.py`, section 6.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from .paths import PROCESSED

__all__ = ["POSTFIRE_WINDOW_YEARS", "load_events", "add_postfire_interval"]

POSTFIRE_WINDOW_YEARS = 2.0


def add_postfire_interval(ev: pd.DataFrame) -> pd.DataFrame:
    """Attach `ignition_date`, `ignition_source` and `years_since_fire`.

    Ignition comes from MTBS where the event matched, otherwise from the
    inventory's own fire start date.
    """
    mt_path = PROCESSED / "inventory" / "pfdf_events_mtbs.csv"
    out = ev.copy()
    out["event_date"] = pd.to_datetime(out["event_date"], errors="coerce")
    out["fire_start_date"] = pd.to_datetime(out.get("fire_start_date"), errors="coerce")
    ign = pd.Series(pd.NaT, index=out.index)
    if mt_path.exists():
        mt = pd.read_csv(mt_path, low_memory=False, parse_dates=["mtbs_ig_date"])
        m = out[["event_id"]].merge(mt[["event_id", "mtbs_ig_date"]], on="event_id",
                                    how="left")
        ign = pd.to_datetime(m.mtbs_ig_date).to_numpy()
        ign = pd.Series(ign, index=out.index)
    out["ignition_source"] = np.where(ign.notna(), "mtbs",
                                      np.where(out.fire_start_date.notna(),
                                               "inventory", "unknown"))
    out["ignition_date"] = ign.fillna(out.fire_start_date)
    out["years_since_fire"] = ((out.event_date - out.ignition_date).dt.days / 365.25)
    return out


def load_events(window_years: float | None = POSTFIRE_WINDOW_YEARS,
                verbose: bool = True) -> pd.DataFrame:
    """Compiled events within the post-fire window.

    `window_years=None` returns everything, for sensitivity tests. Events with
    no ignition date are KEPT (they cannot be judged, and there is only one);
    events dated before their own fire are dropped as impossible.
    """
    ev = pd.read_csv(PROCESSED / "inventory" / "pfdf_events_compiled.csv",
                     low_memory=False, parse_dates=["event_date"])
    ev = add_postfire_interval(ev)
    n0 = len(ev)

    impossible = ev.years_since_fire < 0
    ev = ev[~impossible]

    if window_years is None:
        if verbose:
            print(f"{n0} compiled events; no post-fire window applied "
                  f"({int(impossible.sum())} dropped as dated before their fire)")
        return ev.reset_index(drop=True)

    too_late = ev.years_since_fire > window_years
    kept = ev[~too_late]
    if verbose:
        print(f"{n0} compiled events -> {len(kept)} within {window_years:g} yr of fire "
              f"({int(too_late.sum())} beyond the window, "
              f"{int(impossible.sum())} dated before their fire, "
              f"{int(kept.years_since_fire.isna().sum())} with no ignition date, kept)")
    return kept.reset_index(drop=True)
